services:

  mysql:
    image: mysql:8.0
    container_name: task_mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: Task123

    ports:
      - "3307:3306"

  app:
    build: .
    container_name: smart_task_service

    environment:
      DATABASE_URL: mysql+pymysql://taskuser:Task123@mysql/taskdb

    ports:
      - "5000:5000"

    depends_on:
      - mysql

    restart: always